daru_wheel/urls.py
from .import temp_views as views
from rest_framework.routers import DefaultRouter
from django.urls import path, include
from . import api_view

router = DefaultRouter()
router.register(r'', api_view.StakeViewSet,basename='Stake')


app_name = 'daru_wheel'

urlpatterns = [
    path('stake', include(router.urls)),

    path('', views.spin, name="spin"),
    path('spin_it', views.spin_it, name="spin_it"),

    path('spin', views.daru_spin, name="daru_spin"),
  
]

daruapp/urls.py
from django.contrib import admin
from django.urls import path, include
admin.site.site_header = 'DaruApp Admin'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('dashboard.urls', namespace='dashboard')),
    path('user/', include('users.urls', namespace='users')),
    path('daru_wheel/', include('daru_wheel.urls', namespace='daru_wheel')),
    path('account/', include('account.urls', namespace='account')),
    path('mpesa/', include('mpesa_api.core.urls', 'mpesa')),
]

users/urls.py
from .api_views import UserRecordView
from rest_framework.routers import DefaultRouter

from django.urls import path, re_path, include
from django.contrib.auth import views as auth_views
from . import template_views as views
from django.urls import reverse_lazy

router = DefaultRouter()

app_name = 'users'

urlpatterns = [
    # path('', include(router.urls)),
    path('user/', UserRecordView.as_view(), name='users'),

    path('user_page', views.user_page, name="user_page"),
    path('notification', views.notification, name="notification"),
    path('my_users/', views.mine_users, name="mine_users"),

    path('login', views.CustomLoginView.as_view(), name='login'),
    path('logout', auth_views.LogoutView.as_view(), name='logout'),
    path('register', views.register, name='register'),

    path('password_change/', auth_views.PasswordChangeView.as_view(
        template_name='password/password_change.html'),
        name='password_change'),

    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(
        template_name='password/password_change_done.html'),
        name='password_change_done'),

    path('password_reset/', auth_views.PasswordResetView.as_view(
        template_name='password/password_reset_form.html',
        email_template_name='password/password_reset_email.html',
        subject_template_name='password/password_reset_subject.txt',
        success_url=reverse_lazy('users:password_reset_done'),      
        ), name='password_reset'),

    path('password_reset/done', auth_views.PasswordResetDoneView.as_view(
        template_name='password/password_reset_done.html'),
        name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name='password/password_reset_confirm.html',
        success_url=reverse_lazy('users:password_reset_complete')),
        name='password_reset_confirm'),

    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(
        template_name='password/password_reset_complete.html'),
        name='password_reset_complete'),
]

daru_wheel/models.py
from django.db import models
from django.conf import settings
from django.db.models import Sum
from datetime import timedelta, datetime
from random import randint
from django.utils import timezone
try:
    from account.models import *
except ImportError:
    pass
from django.contrib.auth import get_user_model
from dashboard.models import TimeStamp
User = get_user_model()

class DaruWheelSetting(TimeStamp):
    return_val = models.FloatField(default=0, blank=True, null=True)
    min_redeem_refer_credit = models.FloatField(default=1000, blank=True, null=True)
    refer_per = models.FloatField(default=0, blank=True, null=True)
    per_to_keep = models.FloatField(default=5, blank=True, null=True)
    closed_at = models.FloatField(help_text='sensitive settings value.Dont edit',default=4.7, blank=True, null=True)
    results_at = models.FloatField(help_text='sensitive settings value.Dont edit',default=4.8, blank=True, null=True)
    wheelspin_id = models.IntegerField(help_text='super critical setting value.DONT EDIT!',default=1, blank=True, null=True)
    curr_unit = models.DecimalField(max_digits=6, decimal_places=2, blank=True, null=True)
    min_bet = models.DecimalField(max_digits=5,default=45.9, decimal_places=2, blank=True, null=True)
    win_algo = models.IntegerField(default=1,help_text='1=Random win_RECO,2=Using i win rate  Algo,3=Sure win_to_impress_', blank=True, null=True)
    trial_algo = models.IntegerField(
        default=1,
        help_text='1=Normal win_RECO,2=Super win_to_impress,others=Use_win_algo_above',
        blank=True, null=True)
    big_win_multiplier = models.FloatField(default=10, blank=True, null=True)  
    
    class Meta:
        db_table = "d_daruwheel_setup"

    # @classmethod
    # def get_setup(self, cls):
    #     set_up, _=cls.objects.get_or_create(id=1)
    #     return set_up

def wheel_setting():
    set_up, created = DaruWheelSetting.objects.get_or_create(id=1)
    return set_up

class Selection(TimeStamp):
    name = models.CharField(max_length=100, blank=True, null=True)
    odds = models.FloatField(max_length=10, blank=True, null=True)

    def __str__(self):
        return f'{self.name}'

    @classmethod
    def all_selection(cls):
        return cls.objects.all()

    @classmethod
    def selection_id_list(cls):
        return [_mselect.id for _mselect in cls.objects.all()]

    @classmethod
    def selection_verbose_list(cls):
        return [(_mselect.id, _mselect.name, _mselect.odds) for _mselect in cls.objects.all()]   
  
class WheelSpin(TimeStamp):
    '''Create WheelSpin market instance'''
    open_at = models.DateTimeField(default=timezone.now, blank=True, null=True)
    closed_at = models.DateTimeField(blank=True, null=True)
    results_at = models.DateTimeField(blank=True, null=True)
    
    active = models.BooleanField(default=True, blank=True, null=True)
    per_retun = models.FloatField(default=0, blank=True, null=True)
    receive_results = models.BooleanField(default=False, blank=True, null=True)

    class Meta:
        db_table = "d_wheel_markets"

    def __str__(self):
        return f'WheelSpin No:{self.id}'
        
    @property
    def place_stake_is_active(self):
        try:
            if timezone.now() > self.open_at and \
                 timezone.now() < self.closed_at:
                return True
            return False
        except Exception as e:
            return e

    @property
    def get_result_active(self):
        try:
            if timezone.now() > self.results_at:
                return True
            return False
        except Exception as e:
            return e

    def market_selection_id_list(self):
        try:
            return Selection.selection_id_list()
        except Exception as e:
            return e    

    def total_bet_amount_per_marktinstance(self):
        try:
            total_amount = Stake.objects.filter(
                market_id=self.id,
                bet_on_real_account=True).aggregate(bet_amount=Sum('amount'))
            return total_amount.get('bet_amount')

        except Exception as e:
            return e

    def market_stake_amount(self, select_id):

        try:
            total_amount = Stake.objects.filter(
                market_id=self.id,
                bet_on_real_account=True).filter(
                    marketselection_id=select_id).aggregate(
                        bet_amount=Sum('amount'))

            if total_amount.get('bet_amount'):
                return total_amount.get('bet_amount')
            return 0

        except Exception as e:
            return e

    @property
    def selection_bet_amount(self):
        try:
            mrkt_bet_amount = []
            for selecn in self.market_selection_id_list():
                mrkt_bet_amount.append(self.market_stake_amount(selecn))
            return mrkt_bet_amount
        except Exception as e:
            return e

    @property
    def offset(self):
        try:
            return abs(self.selection_bet_amount[1] - self.selection_bet_amount[0])

        except Exception as e:
            return e

    @property
    def gain_after_relief(self):
        try:
            per_to_return = self.per_retun
            return ((100 - per_to_return)/100)*float(self.offset)
        except Exception as e:
            return e   

    def save(self, *args, **kwargs):
        set_up=wheel_setting()
        self.closed_at = self.open_at + timedelta(minutes=set_up.closed_at)
        self.results_at = self.open_at + timedelta(minutes=set_up.results_at)

        if self.active and not self.place_stake_is_active:
            self.active = False  

        super().save(*args, **kwargs)



class Stake (TimeStamp):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE,related_name='user_wp_istakes',blank =True,null=True)
    market = models.ForeignKey(WheelSpin, on_delete=models.CASCADE,related_name='market_instnces',blank =True,null=True)
    marketselection = models.ForeignKey(Selection, on_delete=models.CASCADE,related_name='imarketselections',blank =True,null=True)#
    amount = models.DecimalField(('amount'), max_digits=12, decimal_places=2, default=50)
    current_bal = models.FloatField(max_length=10,default=0 )#R
    stake_placed = models.BooleanField(blank =True,null=True)#
    has_record = models.BooleanField(blank=True,null=True) #
    has_market = models.BooleanField(default=False, blank=True,null=True)
    bet_on_real_account = models.BooleanField(default=False)
    outcome_received = models.BooleanField(default=False, blank=True,null=True)
    spinned = models.BooleanField(default=False, blank=True,null=True)
    # show_user =  models.BooleanField(default=False, blank=True,null=True)

    def __str__(self):
        return f'stake:{self.amount} by:{self.user}'

    @property
    def this_user_has_cash_to_bet(self):
        set_up=wheel_setting()
        if float(self.amount)> set_up.min_bet: # unti neative values
            if not self.bet_on_real_account:
                try:
                    if current_account_trialbal_of(self.user_id) >=self.amount:
                        return True
                    return False
                except Exception as e:
                    return e    
            else:
                try:
                    if current_account_bal_of(self.user_id) >=self.amount:
                        return True
                    return False
                except Exception as e:
                    return e
        else:
            return False

    def deduct_amount_from_this_user_account(self):
        if not self.bet_on_real_account:
            new_bal = current_account_trialbal_of(self.user_id) - float(self.amount)
            update_account_trialbal_of(self.user_id,new_bal)# F3
        else:
            new_bal = current_account_bal_of(self.user_id) - float(self.amount)
            self.current_bal=new_bal
            update_account_bal_of(self.user_id,new_bal)# F3

    def bet_status(self):
        try:
            try:
                if not self.market:
                    return OutCome.objects.get(stake_id=self.id).win_status
                if  self.marketselection_id== OutCome.objects.get(market_id=self.market.id).result:
                    return 'wind'                    
                return   'losed'
            except  Exception as e:
                print(f'daru_STATUS1 ERROR:{e}')
                return 'pending'                    
        except  Exception as e:
            print(f'daru_STATUS ERROR:{e}')
            return 'pending'

    @classmethod        
    def unspinned(cls,user_id):
        return [obj.id for obj in cls.objects.filter(user=user_id,market=None,spinned=False)]

    @property
    def active_spins(self):
        return self.unspinned(self.user.id)
        # pass

    def save(self, *args, **kwargs):
        ''' Bet could only be registered if user got enoug real or trial balance '''
        if not self.pk:
            if self.this_user_has_cash_to_bet: #then
                self.deduct_amount_from_this_user_account() 
                self.stake_placed= True                   
            else:
                return # no db table record to create!
            try:
                if not self.has_record:
                    log_record(self.user_id,self.amount,'Stake')                    
                    self.has_record = True
            except:
                pass
            if self.market is not None:
                self.has_market =True
            super().save(*args, **kwargs) # create a db record
            
class CashStore(models.Model):
    give_away =  models.DecimalField(('give_away'), max_digits=12, decimal_places=2, default=0)
    to_keep =  models.DecimalField(('to_keep'), max_digits=12, decimal_places=2, default=0)


class OutCome(TimeStamp):
    market  = models.OneToOneField(WheelSpin,on_delete=models.CASCADE,related_name='marketoutcomess',blank =True,null= True)

daru_wheel/forms.py
from django import forms
from .models import Stake

class StakeForm(forms.ModelForm):
    class Meta:
        model = Stake
        fields = (
            'user', 'market', 'marketselection',
            'amount', 'bet_on_real_account')


class IstakeForm(forms.ModelForm):
    class Meta:
        model = Stake
        fields = ('user', 'marketselection', 'amount', 'bet_on_real_account')

daru_wheel/templates/ispin2.html
{% extends "dashboard/layouts/base.html" %}

{% block title %} Daru iSpin {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}

<link rel="stylesheet" href="/static/wheel/css/main.css" type="text/css" />
<!-- <link rel="stylesheet" href="http://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css"> -->

{% endblock stylesheets %}

{% block content %}
<div class="row">
  <div class="col-lg-6 col-md-12">
    <div class="card card-chart">

      <div align="center">
        <table cellpadding="0" cellspacing="0" border="0">
          <tr>
            Spins:{{spins}}
            <td width="438" height="562" class="the_wheel" align="center" valign="center">
              <canvas id="canvas" width="434" height="434">
                <p align="center">Sorry, your browser doesn't support canas.Please try another.</p>
              </canvas>              
            </td>
          </tr>
        </table>
      </div>

      <div align="center" class="col-sm-4"> 
        <!-- <button class="btn btn-fill btn-info" id="spin_button" >BET</button> -->
        <button class="btn btn-fill btn-warning" id="spin_button" >SPIN</button>
      </div>

    </div>
    </div>

    <form method="POST" id="stake-form">
      {% csrf_token %}


<div class="col-lg-6 col-md-12">
  <!-- <div class="card "> -->

    <!-- <div class="col-lg-4"> -->
      <!-- <div class="text-info">{{"Select one"}}</div> -->
      <div class="card card-chart">

        <div class="btn-group btn-group-toggle float-left" data-toggle="buttons" required=True name="marketselection" id="id_marketselection" >
          <!-- <div class="row"> -->
          <label class="btn btn-sm btn-yell btn-simple">
            <input type="radio" class="d-none d-sm-none" name="marketselection" value="2" required=True >                
            <span class="d-none d-sm-block d-md-block d-lg-block d-xl-block">Yellow (x2)</span>
            <span class="d-block d-sm-none">
              <i class="tim-icons icon-gift-2"> Yellow (x2)</i>
            </span>
          </label>        
   
          <label class="btn btn-sm btn-rede btn-simple" >
            <input type="radio" class="d-none" name="marketselection" value="1"  >
            <span class="d-none d-sm-block d-md-block d-lg-block d-xl-block">Red (x2)</span>
            <span class="d-block d-sm-none">
              <i class="tim-icons icon-trophy"> Red (x2)</i>
            </span>
          </label>  
          <!-- </div>    -->

        </div>   

      </div>
    <!-- </div> -->

    <div class="form-group" id="the_stake">
      <input type="number" id="amount_id" class="form-control"  placeholder="Amount to bet" name="amount" required=True >
    </div>
    <div class="btn-group btn-group-toggle float-left" data-toggle="buttons" >
      <label class="btn btn-sm btn-info btn-simple" >
        <div class="form-group:">
          <input type="checkbox" name="bet_on_real_account" id="id_bet_on_real_account" >
        </div>            
        <span class="d-none d-sm-block d-md-block d-lg-block d-xl-block">Bet Real Money</span>
        <span class="d-block d-sm-none">
          <i class="tim-icons icon-wallet-43">Bet Real Money</i>
        </span>
      </label>
    </div>

    <!-- <div class="form-group" > -->
      <button class="btn btn-fill btn-success" type="submit">Bet</button>
    <!-- </div> -->

    
  <!-- </div> -->
</div>  

     </form>

    <div class="card-body">  </div>
  
 </div>

 

   <div class="col-lg-6 col-md-12">
    <div class="card ">
      <div class="card-header">

        <h4 class="card-title"> Stake History</h4>
      </div>
      <div class="card-body">
        <div class="table-responsive">
          <table class="table tablesorter " id="">
            <thead class=" text-primary">
              <tr>
                <th>
                  Time
                </th>
                <th>
                  Choice
                </th>
                <th>
                  Amount
                </th>
                <th class="text-center">
                  Status
                </th>
                <th>
                  Real
                </th>
              </tr>
            </thead>
            <tbody id="talk">
              {%for trans in trans_logz%}
  
              <tr>
                <td>
                  {{trans.created_at}}
                </td>
                <td>
                  {{trans.marketselection}}
                </td>
                <td>
                  {{trans.amount}}
                </td>
                <td class="text-center">
                  {{trans.bet_status}}
                </td>
                <td>
                  {{trans.bet_on_real_account}}
                </td>
              </tr>
              {%endfor%}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>

</div>

      
{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}
<!-- <script src="/static/assets/js/jquery-1.10.2.js" type="text/javascript"></script> -->

<script src="/static/assets/js/vendor/jquery-3.5.1.min.js"></script>
<!-- <script src="/static/wheel/js/reconnecting-websocket.min.js" type="text/javascript"></script> -->
<!-- <script src="/static/scripts/main.js"></script> -->

<script type="text/javascript" src="/static/wheel/js/Winwheel.js"></script>
<!-- <script src="http://cdnjs.cloudflare.com/ajax/libs/gsap/latest/TweenMax.min.js"></script> -->
<script type="text/javascript" src="/static/wheel/js/TweenMax.min.js"></script>
<script type="text/javascript" src="/static/wheel/js/darius.js"></script>

{% endblock javascripts %}