account/urls.py
# om django.contrib.auth.views import LogoutView
from rest_framework.routers import DefaultRouter
# from rest_framework.urlpatterns import format_suffix_patterns
from . import views
from django.urls import path, include
from .template_views import (
    trans_log, refer_credit, mpesa_withrawal, mpesa_deposit,
    cash_trans)


# router = DefaultRouter()

# router.register(r'user', views.UserViewSet)
# router.register(r'custom_users', views.CustomUserViewSet)
# router.register(r'accounts', views.AccountViewSet)
# router.register(r'market', views.MarketInstanceViewSet)
# router.register(r'stake', views.StakeViewSet)
# router.register(r'user_transactions', views.BalanceViewSet)

app_name = 'account'

urlpatterns = [
    # path('', include(router.urls)),
    # path('user/', UserRecordView.as_view(), name='users'),
    path('user_trans/_start=<int:start>&_limit=<int:limit>/_user_id=<int:pk>', views.TransactionView.as_view()),
    #path('rest-auth/', include('rest_auth.urls')),

    # templates
    path('trans_log/', trans_log, name="trans_log"),
    path('refer_credit/', refer_credit, name="refer_credit"),
    path('mpesa_withrawal/', mpesa_withrawal, name="mpesa_withrawal"),
    path('mpesa_deposit/', mpesa_deposit, name="mpesa_deposit"),
    path('cash_trans/', cash_trans, name="cash_trans"),

    
]

daruapp/urls.py
from django.contrib import admin
from django.urls import path, include
admin.site.site_header = 'DaruApp Admin'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('dashboard.urls', namespace='dashboard')),
    path('user/', include('users.urls', namespace='users')),
    path('daru_wheel/', include('daru_wheel.urls', namespace='daru_wheel')),
    path('account/', include('account.urls', namespace='account')),
    path('mpesa/', include('mpesa_api.core.urls', 'mpesa')),
]

dashboard/urls.py
from django.urls import path, re_path
from dashboard import views
from daru_wheel.temp_views import spin
# from daruwheel import views as spinview

app_name = 'dashboard'

urlpatterns = [
    # Matches any html file 
    re_path(r'^.*\.html', views.pages, name='pages'),

    # The home page
    path('', spin, name='index'),
    # path('', views.index, name='index'),
    path('deposit_withraw', views.deposit_withraw, name='deposit_withraw'),
    path('maps', views.maps, name='maps'),
    path('topo', views.topo, name='topo'),
    path('support', views.support, name='support'),

]

users/urls.py
from .api_views import UserRecordView
from rest_framework.routers import DefaultRouter

from django.urls import path, re_path, include
from django.contrib.auth import views as auth_views
from . import template_views as views
from django.urls import reverse_lazy

router = DefaultRouter()

app_name = 'users'

urlpatterns = [
    # path('', include(router.urls)),
    path('user/', UserRecordView.as_view(), name='users'),

    path('user_page', views.user_page, name="user_page"),
    path('notification', views.notification, name="notification"),
    path('my_users/', views.mine_users, name="mine_users"),

    path('login', views.CustomLoginView.as_view(), name='login'),
    path('logout', auth_views.LogoutView.as_view(), name='logout'),
    path('register', views.register, name='register'),

    path('password_change/', auth_views.PasswordChangeView.as_view(
        template_name='password/password_change.html'),
        name='password_change'),

    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(
        template_name='password/password_change_done.html'),
        name='password_change_done'),

    path('password_reset/', auth_views.PasswordResetView.as_view(
        template_name='password/password_reset_form.html',
        email_template_name='password/password_reset_email.html',
        subject_template_name='password/password_reset_subject.txt',
        success_url=reverse_lazy('users:password_reset_done'),      
        ), name='password_reset'),

    path('password_reset/done', auth_views.PasswordResetDoneView.as_view(
        template_name='password/password_reset_done.html'),
        name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name='password/password_reset_confirm.html',
        success_url=reverse_lazy('users:password_reset_complete')),
        name='password_reset_confirm'),

    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(
        template_name='password/password_reset_complete.html'),
        name='password_reset_complete'),
]

dashboard/models.py
from django.db import models

class TimeStamp(models.Model):
    created_at = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    updated_at = models.DateTimeField(auto_now=True, blank=True, null=True)
    # is_active = models.BooleanField(default=True)

    class Meta:
        abstract = True



class WebPa(TimeStamp):
    navbar_eder= models.CharField(max_length=100,default='Daru Wheel', blank =True,null=True)
    footer1= models.CharField(max_length=100,default='Darius & Co.', blank =True,null=True)
    footer2_url= models.CharField(max_length=100,default='https://www.github.com/gibeongideon', blank =True,null=True)
    footer3= models.CharField(max_length=100, blank =True,null=True)
    header1= models.CharField(max_length=100,default='Welcome to Daruwheel', blank =True,null=True)
    header2= models.CharField(max_length=100,default='Play and Win Real Cash', blank =True,null=True)
    header3= models.CharField(max_length=100, blank =True,null=True)
    header4= models.CharField(max_length=100, blank =True,null=True)
    copyright_text= models.CharField(max_length=30, blank =True,null=True)

    mpesa_header_depo_msg = models.TextField(
        max_length=300,
        default='Enter amount and click send.Check M-pesa SMS send to your mobile NO you register with to confirm transaction.',
        blank =True,
        null=True)
    share_info= models.TextField(
        max_length=300,
        default='Share the code to other people to get credit whenever they bet.Once someone register you will always get some credit whenever they place stake.Make sure they entered the code correctly when they signup.',
        blank =True,
        null=True)

dashboard/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from django.template import loader
from django.http import HttpResponse
from django import template


@login_required(login_url="/user/login")
def index(request):
    print(request.user)
    return render(request, "dashboard/index.html")


@login_required(login_url="user/login")
def pages(request):
    context = {}
    # All resource paths end in .html.
    # Pick out the html file name from the url. And load that template.
    try: 
        load_template = request.path.split('/')[-1]
        html_template = loader.get_template(load_template)
        return HttpResponse(html_template.render(context, request))
        
    except template.TemplateDoesNotExist:

        html_template = loader.get_template('error-404.html')
        return HttpResponse(html_template.render(context, request))

    except:

        html_template = loader.get_template('error-500.html')
        return HttpResponse(html_template.render(context, request))


@login_required(login_url="/user/login")
def deposit_withraw(request):

    return render(request, "dashboard/deposit_withraw.html")


@login_required(login_url="/user/login")
def maps(request):
    return render(request, "dashboard/ui-maps.html")


@login_required(login_url="/user/login")
def topo(request):
    return render(request, "dashboard/ui-typography.html")


@login_required(login_url="/user/login")
def support(request):
    return render(request, "dashboard/page-rtl-support.html")

dashboard/templates/dashboard/deposit_withraw.html
{% extends 'dashboard/layouts/base.html' %}

{% block title %} Wallet {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

<div class="row">
  <div class="col-md-12">
    <div class="card">
      <div class="card-header">
        <h5 class="title">Daru Wheel Wallet</h5>
        <!-- <p class="category">Handcrafted by our friends from <a href="/">Daru Wheel</a></p> -->
      </div>
      <div class="card-body all-icons">
        <div class="row">

          <div class="font-icon-list col-lg-2 col-md-3 col-sm-4 col-xs-6 col-xs-6">
            <a href={% url 'account:mpesa_deposit' %} >
              <div class="font-icon-detail">
                <i class="tim-icons icon-simple-add"></i>              
                <p>DEPOSIT</p>
              </div>

            </a>

          </div>
          
          <div class="font-icon-list col-lg-2 col-md-3 col-sm-4 col-xs-6 col-xs-6">
            <a href={% url 'account:mpesa_withrawal' %} >
              <div class="font-icon-detail">
                <i class="tim-icons icon-simple-delete"></i>              
                <p>WITHRAW</p>
              </div>

            </a>

          </div>     

          <div class="font-icon-list col-lg-2 col-md-3 col-sm-4 col-xs-6 col-xs-6">
            <a href={% url 'account:cash_trans' %} >
              <div class="font-icon-detail">
                <i class="tim-icons icon-link-72"></i>
                <p>SEND TO OTHER USER</p>
              </div>
            </div>

            </a>


        </div>
      </div>
    </div>
  </div>
</div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

dashboard/templates/dashboard/error-404.html
{% extends 'dashboard/layouts/base.html' %}

{% block title %} Page 404 {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

    <div class="row">
        <div class="col-md-12">
            <div class="card card-profile">
                <div class="card-body">
                    <h6 class="card-category text-gray">Error 404</h6>
                    <h4 class="card-title">
                        Page not found
                    </h4>
                    <a href="/" class="btn btn-primary btn-round">Home</a>
                </div>
            </div>
        </div>
    </div>


{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

dashboard/templates/dashboard/error-500.html
{% extends 'dashboard/layouts/base.html' %}

{% block title %} Page 404 {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

    <div class="row">
        <div class="col-md-12">
            <div class="card card-profile">
                <div class="card-body">
                    <h6 class="card-category text-gray">Error 500</h6>
                    <h4 class="card-title">
                        Server Error - Please contact support
                    </h4>
                    <a href="/" class="btn btn-primary btn-round">Home</a>
                </div>
            </div>
        </div>
    </div>


{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

dashboard/templates/dashboard/login.html
{% extends "dashboard/layouts/base.html" %}

{% block title %} Login {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

        <div class="row">
          <div class="col-md-8">
            <div class="card">

              <form role="form" method="post" action="">
              
                {% csrf_token %} 

                <div class="card-header">
                  <h5 class="title">Login</h5>

                  <h6 class="card-category">
                      {% if msg %}
                        <span class="text-danger">{{ msg }}</span>
                      {% else %}

                        Use default credentials: test / ApS12_ZZs8
                        <br />
                        OR <a href={% url 'register' %} >create your own user</a>

                      {% endif %}  
                  </h6>
                </div>

                <div class="card-body">

                    <div class="row">

                      <div class="col-md-3 px-md-1">
                        <div class="form-group">
                          <label>Username</label>
                          {{ form.username }}
                        </div>
                      </div>

                    </div>
                    <div class="row">

                      <div class="col-md-3 px-md-1">
                        <div class="form-group">
                          <label>Password</label>
                          {{ form.password }}
                        </div>
                      </div>

                    </div>
                    
                </div>
                <div class="card-footer">
                  <button type="submit" name="login" class="btn btn-fill btn-primary">Login</button>
                  &nbsp; &nbsp;
                  Don't have an account? <a href="{% url 'register' %}" class="text-primary">Create</a>
                </div>

              </form>

            </div>
          </div>
      </div>


{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

dashboard/templates/dashboard/page-blank.html
{% extends 'dashboard/layouts/base.html' %}

{% block title %} Page Blank {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

    <div class="row">
        <div class="col-md-12">
            <div class="card card-profile">
                <div class="card-body">
                    <h6 class="card-category text-gray">Page Blank</h6>
                    <h4 class="card-title">
                        Add your content 
                    </h4>
                    <a href="/" class="btn btn-primary btn-round">Home</a>
                </div>
            </div>
        </div>
    </div>
    
{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

dashboard/templates/dashboard/register.html
{% extends "dashboard/layouts/base.html" %}

{% block title %} Register {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

        <div class="row">
          <div class="col-md-8">
            <div class="card">

              <form role="form" method="post" action="">
              
                {% csrf_token %} 

                <div class="card-header">
                  <h5 class="title">Register</h5>

                  <h6 class="card-category">
                      {% if msg %}
                        <span class="text-danger">{{ msg }}</span>
                      {% else %}
                        Add your credentials or <a href={% url 'login' %} >authenticate</a> with an existing account.
                      {% endif %}  
                  </h6>
                </div>

              {% if success %}

                <p>
                  Please <a href={% url 'login' %}>authenticate</a> using the new account.
                </p>  

              {% else %}

                <div class="card-body">

                    <div class="row">
                      <div class="col-md-3 px-md-1">
                        <div class="form-group">
                          <label>Username</label>
                          {{ form.username }}
                        </div>
                      </div>
                    </div>
                    <span class="text-danger">{{ form.username.errors }}</span>

                    <div class="row">
                      <div class="col-md-3 px-md-1">
                        <div class="form-group">
                          <label>Email</label>
                          {{ form.email }}
                        </div>
                      </div>
                    </div>
                    <span class="text-danger">{{ form.email.errors }}</span>

                    <div class="row">
                      <div class="col-md-3 px-md-1">
                        <div class="form-group">
                          <label>Password</label>
                          {{ form.password1 }}
                        </div>
                      </div>
                    </div>
                    <span class="text-danger">{{ form.password1.errors }}</span>
                    
                    <div class="row">
                        <div class="col-md-3 px-md-1">
                            <div class="form-group">
                            <label>Password Check</label>
                            {{ form.password2 }}
                            </div>
                        </div>
                    </div>
                    <span class="text-danger">{{ form.password2.errors }}</span>

                </div>
                <div class="card-footer">
                  <button type="submit" name="register" class="btn btn-fill btn-primary">Register</button>
                  &nbsp; &nbsp;
                  Have an account? <a href="{% url 'login' %}" class="text-primary">Login</a>
                </div>

              {% endif %} 

              </form>

            </div>
          </div>
      </div>


{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

dashboard/templates/dashboard/ui-notifications.html
{% extends 'dashboard/layouts/base.html' %}

{% block title %} UI Notifications {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

<div class="row">
  <div class="col-md-6">
    <div class="card">
      <div class="card-header">
        <h4 class="card-title">Notifications Style</h4>
      </div>
      <div class="card-body">
        <div class="alert alert-info">
          <span>This is a plain notification</span>
        </div>
        <div class="alert alert-info">
          <button type="button" aria-hidden="true" class="close" data-dismiss="alert" aria-label="Close">
            <i class="tim-icons icon-simple-remove"></i>
          </button>
          <span>This is a notification with close button.</span>
        </div>
        <div class="alert alert-info alert-with-icon" data-notify="container">
          <button type="button" aria-hidden="true" class="close" data-dismiss="alert" aria-label="Close">
            <i class="tim-icons icon-simple-remove"></i>
          </button>
          <span data-notify="icon" class="tim-icons icon-bell-55"></span>
          <span data-notify="message">This is a notification with close button and icon.</span>
        </div>
        <div class="alert alert-info alert-with-icon" data-notify="container">
          <button type="button" aria-hidden="true" class="close" data-dismiss="alert" aria-label="Close">
            <i class="tim-icons icon-simple-remove"></i>
          </button>
          <span data-notify="icon" class="tim-icons icon-bell-55"></span>
          <span data-notify="message">This is a notification with close button and icon and have many lines. You can see that the icon and the close button are always vertically aligned. This is a beautiful notification. So you don't have to worry about the style.</span>
        </div>
      </div>
    </div>
  </div>
  <div class="col-md-6">
    <div class="card">
      <div class="card-header">
        <h4 class="card-title">Notification states</h4>
      </div>
      <div class="card-body">
        <div class="alert alert-primary">
          <button type="button" aria-hidden="true" class="close" data-dismiss="alert" aria-label="Close">
            <i class="tim-icons icon-simple-remove"></i>
          </button>
          <span><b> Primary - </b> This is a regular notification made with ".alert-primary"</span>
        </div>
        <div class="alert alert-info">
          <button type="button" aria-hidden="true" class="close" data-dismiss="alert" aria-label="Close">
            <i class="tim-icons icon-simple-remove"></i>
          </button>
          <span><b> Info - </b> This is a regular notification made with ".alert-info"</span>
        </div>
        <div class="alert alert-success">
          <button type="button" aria-hidden="true" class="close" data-dismiss="alert" aria-label="Close">
            <i class="tim-icons icon-simple-remove"></i>
          </button>
          <span><b> Success - </b> This is a regular notification made with ".alert-success"</span>
        </div>
        <div class="alert alert-warning">
          <button type="button" aria-hidden="true" class="close" data-dismiss="alert" aria-label="Close">
            <i class="tim-icons icon-simple-remove"></i>
          </button>
          <span><b> Warning - </b> This is a regular notification made with ".alert-warning"</span>
        </div>
        <div class="alert alert-danger">
          <button type="button" aria-hidden="true" class="close" data-dismiss="alert" aria-label="Close">
            <i class="tim-icons icon-simple-remove"></i>
          </button>
          <span><b> Danger - </b> This is a regular notification made with ".alert-danger"</span>
        </div>
      </div>
    </div>
  </div>
  <div class="col-md-12">
    <div class="card">
      <div class="card-body">
        <div class="places-buttons">
          <div class="row">
            <div class="col-md-6 ml-auto mr-auto text-center">
              <h4 class="card-title">
                Notifications Places
                <p class="category">Click to view notifications</p>
              </h4>
            </div>
          </div>
          <div class="row">
            <div class="col-lg-8 ml-auto mr-auto">
              <div class="row">
                <div class="col-md-4">
                  <button class="btn btn-primary btn-block" onclick="demo.showNotification('top','left')">Top Left</button>
                </div>
                <div class="col-md-4">
                  <button class="btn btn-primary btn-block" onclick="demo.showNotification('top','center')">Top Center</button>
                </div>
                <div class="col-md-4">
                  <button class="btn btn-primary btn-block" onclick="demo.showNotification('top','right')">Top Right</button>
                </div>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-lg-8 ml-auto mr-auto">
              <div class="row">
                <div class="col-md-4">
                  <button class="btn btn-primary btn-block" onclick="demo.showNotification('bottom','left')">Bottom Left</button>
                </div>
                <div class="col-md-4">
                  <button class="btn btn-primary btn-block" onclick="demo.showNotification('bottom','center')">Bottom Center</button>
                </div>
                <div class="col-md-4">
                  <button class="btn btn-primary btn-block" onclick="demo.showNotification('bottom','right')">Bottom Right</button>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

dashboard/templates/dashboard/ui-typography.html
{% extends 'dashboard/layouts/base.html' %}

{% block title %} UI Typography {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

<div class="row">
  <div class="col-md-12">
    <div class="card">
      <div class="card-header mb-5">
        <h5 class="card-category">Black Table Heading</h5>
        <h3 class="card-title">Created using Poppins Font Family</h3>
      </div>
      <div class="card-body">
        <div class="typography-line">
          <h1><span>Header 1</span>The Life of Black Dashboard </h1>
        </div>
        <div class="typography-line">
          <h2><span>Header 2</span>The Life of Black Dashboard </h2>
        </div>
        <div class="typography-line">
          <h3><span>Header 3</span>The Life of Black Dashboard </h3>
        </div>
        <div class="typography-line">
          <h4><span>Header 4</span>The Life of Black Dashboard </h4>
        </div>
        <div class="typography-line">
          <h5><span>Header 5</span>The Life of Black Dashboard </h5>
        </div>
        <div class="typography-line">
          <h6><span>Header 6</span>The Life of Black Dashboard </h6>
        </div>
        <div class="typography-line">
          <p><span>Paragraph</span>
            I will be the leader of a company that ends up being worth billions of dollars, because I got the answers. I understand culture. I am the nucleus. I think that’s a responsibility that I have, to push possibilities, to show people, this is the level that things could be at.
          </p>
        </div>
        <div class="typography-line">
          <span>Quote</span>
          <blockquote>
            <p class="blockquote blockquote-primary">
              "I will be the leader of a company that ends up being worth billions of dollars, because I got the answers. I understand culture. I am the nucleus. I think that’s a responsibility that I have, to push possibilities, to show people, this is the level that things could be at."
              <br>
              <br>
              <small>
                - Noaa
              </small>
            </p>
          </blockquote>
        </div>
        <div class="typography-line">
          <span>Muted Text</span>
          <p class="text-muted">
            I will be the leader of a company that ends up being worth billions of dollars, because I got the answers...
          </p>
        </div>
        <div class="typography-line">
          <span>Primary Text</span>
          <p class="text-primary">
            I will be the leader of a company that ends up being worth billions of dollars, because I got the answers...</p>
        </div>
        <div class="typography-line">
          <span>Info Text</span>
          <p class="text-info">
            I will be the leader of a company that ends up being worth billions of dollars, because I got the answers... </p>
        </div>
        <div class="typography-line">
          <span>Success Text</span>
          <p class="text-success">
            I will be the leader of a company that ends up being worth billions of dollars, because I got the answers... </p>
        </div>
        <div class="typography-line">
          <span>Warning Text</span>
          <p class="text-warning">
            I will be the leader of a company that ends up being worth billions of dollars, because I got the answers...
          </p>
        </div>
        <div class="typography-line">
          <span>Danger Text</span>
          <p class="text-danger">
            I will be the leader of a company that ends up being worth billions of dollars, because I got the answers... </p>
        </div>
        <div class="typography-line">
          <h2><span>Small Tag</span>
            Header with small subtitle <br>
            <small>Use "small" tag for the headers</small>
          </h2>
        </div>
        <div class="typography-line">
          <span>Lists</span>
          <div class="row">
            <div class="col-md-3">
              <h5>Unordered List</h5>
              <ul>
                <li>List Item</li>
                <li>List Item</li>
                <li class="list-unstyled">
                  <ul>
                    <li>List Item</li>
                    <li>List Item</li>
                    <li>List Item</li>
                  </ul>
                </li>
                <li>List Item</li>
              </ul>
            </div>
            <div class="col-md-3">
              <h5>Ordered List</h5>
              <ol>
                <li>List Item</li>
                <li>List Item</li>
                <li>List item</li>
                <li>List Item</li>
              </ol>
            </div>
            <div class="col-md-3">
              <h5>Unstyled List</h5>
              <ul class="list-unstyled">
                <li>List Item</li>
                <li>List Item</li>
                <li>List item</li>
                <li>List Item</li>
              </ul>
            </div>
            <div class="col-md-3">
              <h5>Inline List</h5>
              <ul class="list-inline">
                <li class="list-inline-item">List1</li>
                <li class="list-inline-item">List2</li>
                <li class="list-inline-item">List3</li>
              </ul>
            </div>
          </div>
        </div>
        <div class="typography-line">
          <span>Code</span>
          <p>This is
            <code>.css-class-as-code</code>, an example of an inline code element. Wrap inline code within a
            <code> &lt;code&gt;...&lt;/code&gt;</code>tag.
          </p>
          <pre>1. #This is an example of preformatted text.<br/>2. #Here is another line of code</pre>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}