account/urls.py
# om django.contrib.auth.views import LogoutView
from rest_framework.routers import DefaultRouter
# from rest_framework.urlpatterns import format_suffix_patterns
from . import views
from django.urls import path, include
from .template_views import (
    trans_log, refer_credit, mpesa_withrawal, mpesa_deposit,
    cash_trans)


# router = DefaultRouter()

# router.register(r'user', views.UserViewSet)
# router.register(r'custom_users', views.CustomUserViewSet)
# router.register(r'accounts', views.AccountViewSet)
# router.register(r'market', views.MarketInstanceViewSet)
# router.register(r'stake', views.StakeViewSet)
# router.register(r'user_transactions', views.BalanceViewSet)

app_name = 'account'

urlpatterns = [
    # path('', include(router.urls)),
    # path('user/', UserRecordView.as_view(), name='users'),
    path('user_trans/_start=<int:start>&_limit=<int:limit>/_user_id=<int:pk>', views.TransactionView.as_view()),
    #path('rest-auth/', include('rest_auth.urls')),

    # templates
    path('trans_log/', trans_log, name="trans_log"),
    path('refer_credit/', refer_credit, name="refer_credit"),
    path('mpesa_withrawal/', mpesa_withrawal, name="mpesa_withrawal"),
    path('mpesa_deposit/', mpesa_deposit, name="mpesa_deposit"),
    path('cash_trans/', cash_trans, name="cash_trans"),

    
]

daru_wheel/urls.py
from .import temp_views as views
from rest_framework.routers import DefaultRouter
from django.urls import path, include
from . import api_view

router = DefaultRouter()
router.register(r'', api_view.StakeViewSet,basename='Stake')


app_name = 'daru_wheel'

urlpatterns = [
    path('stake', include(router.urls)),

    path('', views.spin, name="spin"),
    path('spin_it', views.spin_it, name="spin_it"),

    path('spin', views.daru_spin, name="daru_spin"),
  
]

daruapp/urls.py
from django.contrib import admin
from django.urls import path, include
admin.site.site_header = 'DaruApp Admin'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('dashboard.urls', namespace='dashboard')),
    path('user/', include('users.urls', namespace='users')),
    path('daru_wheel/', include('daru_wheel.urls', namespace='daru_wheel')),
    path('account/', include('account.urls', namespace='account')),
    path('mpesa/', include('mpesa_api.core.urls', 'mpesa')),
]

dashboard/urls.py
from django.urls import path, re_path
from dashboard import views
from daru_wheel.temp_views import spin
# from daruwheel import views as spinview

app_name = 'dashboard'

urlpatterns = [
    # Matches any html file 
    re_path(r'^.*\.html', views.pages, name='pages'),

    # The home page
    path('', spin, name='index'),
    # path('', views.index, name='index'),
    path('deposit_withraw', views.deposit_withraw, name='deposit_withraw'),
    path('maps', views.maps, name='maps'),
    path('topo', views.topo, name='topo'),
    path('support', views.support, name='support'),

]

users/urls.py
from .api_views import UserRecordView
from rest_framework.routers import DefaultRouter

from django.urls import path, re_path, include
from django.contrib.auth import views as auth_views
from . import template_views as views
from django.urls import reverse_lazy

router = DefaultRouter()

app_name = 'users'

urlpatterns = [
    # path('', include(router.urls)),
    path('user/', UserRecordView.as_view(), name='users'),

    path('user_page', views.user_page, name="user_page"),
    path('notification', views.notification, name="notification"),
    path('my_users/', views.mine_users, name="mine_users"),

    path('login', views.CustomLoginView.as_view(), name='login'),
    path('logout', auth_views.LogoutView.as_view(), name='logout'),
    path('register', views.register, name='register'),

    path('password_change/', auth_views.PasswordChangeView.as_view(
        template_name='password/password_change.html'),
        name='password_change'),

    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(
        template_name='password/password_change_done.html'),
        name='password_change_done'),

    path('password_reset/', auth_views.PasswordResetView.as_view(
        template_name='password/password_reset_form.html',
        email_template_name='password/password_reset_email.html',
        subject_template_name='password/password_reset_subject.txt',
        success_url=reverse_lazy('users:password_reset_done'),      
        ), name='password_reset'),

    path('password_reset/done', auth_views.PasswordResetDoneView.as_view(
        template_name='password/password_reset_done.html'),
        name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name='password/password_reset_confirm.html',
        success_url=reverse_lazy('users:password_reset_complete')),
        name='password_reset_confirm'),

    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(
        template_name='password/password_reset_complete.html'),
        name='password_reset_complete'),
]

dashboard/models.py
from django.db import models

class TimeStamp(models.Model):
    created_at = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    updated_at = models.DateTimeField(auto_now=True, blank=True, null=True)
    # is_active = models.BooleanField(default=True)

    class Meta:
        abstract = True



class WebPa(TimeStamp):
    navbar_eder= models.CharField(max_length=100,default='Daru Wheel', blank =True,null=True)
    footer1= models.CharField(max_length=100,default='Darius & Co.', blank =True,null=True)
    footer2_url= models.CharField(max_length=100,default='https://www.github.com/gibeongideon', blank =True,null=True)
    footer3= models.CharField(max_length=100, blank =True,null=True)
    header1= models.CharField(max_length=100,default='Welcome to Daruwheel', blank =True,null=True)
    header2= models.CharField(max_length=100,default='Play and Win Real Cash', blank =True,null=True)
    header3= models.CharField(max_length=100, blank =True,null=True)
    header4= models.CharField(max_length=100, blank =True,null=True)
    copyright_text= models.CharField(max_length=30, blank =True,null=True)

    mpesa_header_depo_msg = models.TextField(
        max_length=300,
        default='Enter amount and click send.Check M-pesa SMS send to your mobile NO you register with to confirm transaction.',
        blank =True,
        null=True)
    share_info= models.TextField(
        max_length=300,
        default='Share the code to other people to get credit whenever they bet.Once someone register you will always get some credit whenever they place stake.Make sure they entered the code correctly when they signup.',
        blank =True,
        null=True)

dashboard/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from django.template import loader
from django.http import HttpResponse
from django import template


@login_required(login_url="/user/login")
def index(request):
    print(request.user)
    return render(request, "dashboard/index.html")


@login_required(login_url="user/login")
def pages(request):
    context = {}
    # All resource paths end in .html.
    # Pick out the html file name from the url. And load that template.
    try: 
        load_template = request.path.split('/')[-1]
        html_template = loader.get_template(load_template)
        return HttpResponse(html_template.render(context, request))
        
    except template.TemplateDoesNotExist:

        html_template = loader.get_template('error-404.html')
        return HttpResponse(html_template.render(context, request))

    except:

        html_template = loader.get_template('error-500.html')
        return HttpResponse(html_template.render(context, request))


@login_required(login_url="/user/login")
def deposit_withraw(request):

    return render(request, "dashboard/deposit_withraw.html")


@login_required(login_url="/user/login")
def maps(request):
    return render(request, "dashboard/ui-maps.html")


@login_required(login_url="/user/login")
def topo(request):
    return render(request, "dashboard/ui-typography.html")


@login_required(login_url="/user/login")
def support(request):
    return render(request, "dashboard/page-rtl-support.html")

dashboard/templates/dashboard/includes/fixed-plugin.html
<!-- 
  <div class="fixed-plugin">
    <div class="dropdown show-dropdown">
      <a href="#" data-toggle="dropdown">
        <i class="fa fa-cog fa-2x"> </i>
      </a>
      <ul class="dropdown-menu">
        <li class="header-title"> Sidebar Background</li>
        <li class="adjustments-line">
          <a href="javascript:void(0)" class="switch-trigger background-color">
            <div class="badge-colors text-center">
              <span class="badge filter badge-primary active" data-color="primary"></span>
              <span class="badge filter badge-info" data-color="blue"></span>
              <span class="badge filter badge-success" data-color="green"></span>
            </div>
            <div class="clearfix"></div>
          </a>
        </li>
        <li class="adjustments-line text-center color-change">
          <span class="color-label">DARK MODE</span>
          <span class="badge dark-badge ml-2"></span>
          <span class="badge light-badge mr-2"></span>
          <span class="color-label">LIGHT MODE</span>
        </li>
      </ul>

      <br />
    </div>
  </div>
   -->


   <div class="fixed-plugin">

        <div class="adjustments-line text-center color-change">
          <span class="color-label">light mode</span>
          <span class="badge light-badge mr-2"></span>
        </div>

  </div>
     

dashboard/templates/dashboard/includes/footer.html
  <footer class="footer">
    <div class="container-fluid">
      <ul class="nav">
        <li class="nav-item">
          <a target="_blank" 
             href="{% url 'daru_wheel:daru_spin' %}" class="nav-link">
             Daru Wheel for Real Cash
          </a>
        </li>
      </ul>
      <div class="copyright">
        &copy; <a target="_blank" 
                  href="https://www.github.com/gibeongideon">Darius & Co.</a>
         <!-- -visit <a target="_blank" href="https://www.github.com/gibeongideon">gibeongideon</a>. -->
      </div>
    </div>
  </footer>

dashboard/templates/dashboard/includes/header.html
  <footer class="footer">
    <!-- <div class="container-fluid"> -->
      <ul class="nav">
        <li class="nav-item">
          <h3 class="text-info">
            <span>Welcome to Daruwheel</span>
          </h3>

        </li>
      </ul>
      <div class="copyright">
        <h4 class="text-primary">Play and Win Real Cash</h4>

      </div>
    <!-- </div> -->
  </footer>

dashboard/templates/dashboard/includes/navigation.html
<!-- Static assets -->
{% load static %}

      <!-- Navbar -->
      <nav class="navbar navbar-expand-lg navbar-absolute navbar-transparent">
        <div class="container-fluid">
          <div class="navbar-wrapper">
            <div class="navbar-toggle d-inline">
              <button type="button" class="navbar-toggler">
                <span class="navbar-toggler-bar bar1"></span>
                <span class="navbar-toggler-bar bar2"></span>
                <span class="navbar-toggler-bar bar3"></span>
              </button>
            </div>
            <a class="navbar-brand" href="javascript:void(0)">Daru Wheel</a>
          </div>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navigation" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-bar navbar-kebab"></span>
            <span class="navbar-toggler-bar navbar-kebab"></span>
            <span class="navbar-toggler-bar navbar-kebab"></span>
          </button>
          <div class="collapse navbar-collapse" id="navigation">

            {% if user.is_authenticated %}
            <ul class="navbar-nav ml-auto">

              <!-- <li class="search-bar input-group">
                <button class="btn btn-link" id="search-button" data-toggle="modal" data-target="#searchModal"><i class="tim-icons icon-zoom-split" ></i>
                  <span class="d-lg-none d-md-block">Deposit</span>
                </button>
              </li> -->

            <li class="dropdown nav-item">
              <a href="{% url 'dashboard:deposit_withraw' %}" >
                <button class="btn " >                  
                  <i class="tim-icons icon-credit-card" ></i>
                  <span class="d-lg-none d-md-block"><p class='text-info'>Deposit & Withraw</p></span>
                  <span class="d-none d-sm-block d-md-block d-lg-block d-xl-block"><h6 class='text-info'>Deposit & Withraw</h6></span>             

              </button> 
              </a>    
             
            </li>  

            <li class="separator d-lg-none"></li>





              <li class="dropdown nav-item">
                <a href="javascript:void(0)" class="dropdown-toggle nav-link" data-toggle="dropdown">
                  <div class="notification d-none d-lg-block d-xl-block"></div>
                  <i class="tim-icons icon-money-coins"></i>
                  <p class="d-lg-none">
                   {{user.user_accounts.balance}}
                  </p>
                </a>
                <ul class="dropdown-menu dropdown-menu-right dropdown-navbar">
                  <li class="nav-link"><a href="{% url 'dashboard:deposit_withraw' %}" class="nav-item dropdown-item"><h5 class="text-info">Actual Balance: {{user.user_accounts.balance}}</h5></a></li>
                  <li class="nav-link"><a href="{% url 'dashboard:deposit_withraw' %}" class="nav-item dropdown-item"><h5 class="text-info"> Withrawable Balannce: {{user.user_accounts.withrawable_balance}}</h5></a></li>
                  <li class="nav-link"><a href="{% url 'dashboard:deposit_withraw' %}" class="nav-item dropdown-item"><h5 class="text-info"> Withraw Power: {{user.user_accounts.withraw_power}}</h5></a></li>
                  <li class="nav-link"><a href="javascript:void(0)" class="nav-item dropdown-item"><h5 class="text-info">Refer Balance: {{user.user_accounts.refer_balance}}</h5></a></li>
                  <li class="nav-link"><a href="javascript:void(0)" class="nav-item dropdown-item"><h5 class="text-info">Trial Balance: {{user.user_accounts.trial_balance}}</h5></a></li>
            
                </ul>
              </li>
              <li class="dropdown nav-item">
                <a href="#" class="dropdown-toggle nav-link" data-toggle="dropdown">
                  <div class="photo">
                    <img src="{% static 'assets/img/duser.png' %}" alt="Profile Photo">
                  </div>
                  <b class="caret d-none d-lg-block d-xl-block"></b>
                  <p class="d-lg-none">
                    Log out
                  </p>
                </a>
                <ul class="dropdown-menu dropdown-navbar">
                  <li class="nav-link"><a href="{% url 'users:user_page' %}" class="nav-item dropdown-item"><h5 class="text-info">Profile ({{request.user.username}})</h5></a></li>
                  <li class="dropdown-divider"></li>
                  <li class="nav-link"><a href="{% url 'users:logout' %}" class="nav-item dropdown-item"><h5 class="text-danger">Log out</h5></a></li>
                </ul>
              </li>
              <li class="separator d-lg-none"></li>
            </ul>
            {% endif %}

          </div>
        </div>
      </nav>
      <div class="modal modal-search fade" id="searchModal" tabindex="-1" role="dialog" aria-labelledby="searchModal" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <input type="text" class="form-control" id="inlineFormInputGroup" placeholder="SEARCH">
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <i class="tim-icons icon-simple-remove"></i>
              </button>
            </div>
          </div>
        </div>
      </div>
      <!-- End Navbar -->

dashboard/templates/dashboard/includes/scripts-sidebar.html
  <script>
    $(document).ready(function() {
      $().ready(function() {
        $sidebar = $('.sidebar');
        $navbar = $('.navbar');
        $main_panel = $('.main-panel');

        $full_page = $('.full-page');

        $sidebar_responsive = $('body > .navbar-collapse');
        sidebar_mini_active = true;
        white_color = false;

        window_width = $(window).width();

        fixed_plugin_open = $('.sidebar .sidebar-wrapper .nav li.active a p').html();



        $('.fixed-plugin a').click(function(event) {
          if ($(this).hasClass('switch-trigger')) {
            if (event.stopPropagation) {
              event.stopPropagation();
            } else if (window.event) {
              window.event.cancelBubble = true;
            }
          }
        });

        $('.fixed-plugin .background-color span').click(function() {
          $(this).siblings().removeClass('active');
          $(this).addClass('active');

          var new_color = $(this).data('color');

          if ($sidebar.length != 0) {
            $sidebar.attr('data', new_color);
          }

          if ($main_panel.length != 0) {
            $main_panel.attr('data', new_color);
          }

          if ($full_page.length != 0) {
            $full_page.attr('filter-color', new_color);
          }

          if ($sidebar_responsive.length != 0) {
            $sidebar_responsive.attr('data', new_color);
          }
        });

        $('.switch-sidebar-mini input').on("switchChange.bootstrapSwitch", function() {
          var $btn = $(this);

          if (sidebar_mini_active == true) {
            $('body').removeClass('sidebar-mini');
            sidebar_mini_active = false;
            blackDashboard.showSidebarMessage('Sidebar mini deactivated...');
          } else {
            $('body').addClass('sidebar-mini');
            sidebar_mini_active = true;
            blackDashboard.showSidebarMessage('Sidebar mini activated...');
          }

          // we simulate the window Resize so the charts will get updated in realtime.
          var simulateWindowResize = setInterval(function() {
            window.dispatchEvent(new Event('resize'));
          }, 180);

          // we stop the simulation of Window Resize after the animations are completed
          setTimeout(function() {
            clearInterval(simulateWindowResize);
          }, 1000);
        });

        $('.switch-change-color input').on("switchChange.bootstrapSwitch", function() {
          var $btn = $(this);

          if (white_color == true) {

            $('body').addClass('change-background');
            setTimeout(function() {
              $('body').removeClass('change-background');
              $('body').removeClass('white-content');
            }, 900);
            white_color = false;
          } else {

            $('body').addClass('change-background');
            setTimeout(function() {
              $('body').removeClass('change-background');
              $('body').addClass('white-content');
            }, 900);

            white_color = true;
          }


        });

        $('.light-badge').click(function() {
          $('body').addClass('white-content');
        });

        $('.dark-badge').click(function() {
          $('body').removeClass('white-content');
        });
      });
    });
  </script>
  

dashboard/templates/dashboard/includes/scripts.html
<!-- Static assets -->
{% load static %}

  <!--   Core JS Files   -->
  <script src="{% static 'assets/js/core/jquery.min.js' %}"></script>
  <script src="{% static 'assets/js/core/popper.min.js' %}"></script>
  <script src="{% static 'assets/js/core/bootstrap.min.js' %}"></script>
  <script src="{% static 'assets/js/plugins/perfect-scrollbar.jquery.min.js' %}"></script>

  <script src="{% static 'assets/js/plugins/chartjs.min.js' %}"></script>
  <!--  Notifications Plugin    -->
  <script src="{% static 'assets/js/plugins/bootstrap-notify.js' %}"></script>
  <!-- Control Center for Black Dashboard: parallax effects, scripts for the example pages etc -->
  <script src="{% static 'assets/js/black-dashboard.min.js' %}"></script>

dashboard/templates/dashboard/includes/sidebar.html
    <div class="sidebar">
      <div class="sidebar-wrapper">
        
        <div class="logo">
          <a target="_blank" 
             href="https://www.daruandwheel.com" class="simple-text logo-mini">
            
          </a>
          <a target="_blank" 
             href="https://www.daruandwheel.com" class="simple-text logo-normal">
            Daru Menu
          </a>
        </div>

        {% if user.is_authenticated %}
        <ul class="nav">
          <li class="active ">
            <a href="{% url 'daru_wheel:spin' %}">
              <i class="tim-icons icon-align-center"></i>
              <p>iSpin</p>
            </a>
          </li>

          <li>
            <a href="{% url 'daru_wheel:daru_spin' %}">
              <i class="tim-icons icon-support-17"></i>
              <p>Daru Wheel</p>
            </a>
          </li>

          <!-- <li>
            <a href="{% url 'daru_wheel:daru_spin' %}">
              <i class="tim-icons icon-support-17"></i>
              <p>Daru Wheel</p>
            </a>
          </li> -->

          <li>
            <a href= "{% url 'users:mine_users' %}">
              <i class="tim-icons icon-badge"></i>
              <p>My Users</p>
            </a>
          </li>
          <li>
            <a href= "{% url 'account:refer_credit' %}">
              <i class="tim-icons icon-badge"></i>
              <p>My Users Income</p>
            </a>
          </li>
          <li>

            <a href="{% url 'account:trans_log' %}">
              <i class="tim-icons icon-bullet-list-67"></i>
              <p>Transactions Log</p>
            </a>
          </li>
          <li>
            <a href="{% url 'dashboard:deposit_withraw' %}">
              <i class="tim-icons icon-wallet-43"></i>
              <p>Wallet</p>
            </a>
          </li>


          <!-- <li>
            <a href="">
              <i class="tim-icons icon-bell-55"></i>
              <p>Notifications</p>
            </a>
          </li>

          <li>
            <a href="">
              <i class="tim-icons icon-align-center"></i>
              <p>Share</p>
            </a>
          </li>
           -->
          <li>
            <a href="{% url 'users:user_page' %}">
              <i class="tim-icons icon-single-02"></i>
              <p>User Profile</p>
            </a>
          </li>

          <li class="active-pro">
            <a href="{% url 'users:logout' %}" >
              <i class="tim-icons icon-user-run"></i>
              <p>Logout</p>
            </a>
          </li>

        </ul>
        {% endif %}
        
      </div>
    </div>