daruapp/urls.py
from django.contrib import admin
from django.urls import path, include
admin.site.site_header = 'DaruApp Admin'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('dashboard.urls', namespace='dashboard')),
    path('user/', include('users.urls', namespace='users')),
    path('daru_wheel/', include('daru_wheel.urls', namespace='daru_wheel')),
    path('account/', include('account.urls', namespace='account')),
    path('mpesa/', include('mpesa_api.core.urls', 'mpesa')),
]

users/urls.py
from .api_views import UserRecordView
from rest_framework.routers import DefaultRouter

from django.urls import path, re_path, include
from django.contrib.auth import views as auth_views
from . import template_views as views
from django.urls import reverse_lazy

router = DefaultRouter()

app_name = 'users'

urlpatterns = [
    # path('', include(router.urls)),
    path('user/', UserRecordView.as_view(), name='users'),

    path('user_page', views.user_page, name="user_page"),
    path('notification', views.notification, name="notification"),
    path('my_users/', views.mine_users, name="mine_users"),

    path('login', views.CustomLoginView.as_view(), name='login'),
    path('logout', auth_views.LogoutView.as_view(), name='logout'),
    path('register', views.register, name='register'),

    path('password_change/', auth_views.PasswordChangeView.as_view(
        template_name='password/password_change.html'),
        name='password_change'),

    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(
        template_name='password/password_change_done.html'),
        name='password_change_done'),

    path('password_reset/', auth_views.PasswordResetView.as_view(
        template_name='password/password_reset_form.html',
        email_template_name='password/password_reset_email.html',
        subject_template_name='password/password_reset_subject.txt',
        success_url=reverse_lazy('users:password_reset_done'),      
        ), name='password_reset'),

    path('password_reset/done', auth_views.PasswordResetDoneView.as_view(
        template_name='password/password_reset_done.html'),
        name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name='password/password_reset_confirm.html',
        success_url=reverse_lazy('users:password_reset_complete')),
        name='password_reset_confirm'),

    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(
        template_name='password/password_reset_complete.html'),
        name='password_reset_complete'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
import uuid


class User(AbstractUser):
    """Add three fields to existing Django User model.
      : referer_code  , code n 4ne-nuber for reference
    """
    code = models.CharField(max_length=150,unique=True,null=True)
    referer_code = models.CharField(max_length=150, blank=True, null=True)
    phone_number = models.CharField(max_length=150, blank=True, null=True)
    active = models.BooleanField(default=True)

    def __str__(self):
        return self.username

    @staticmethod
    def format_mobile_no(mobile): # hard coded for kenya # need refactor
        mobile = str(mobile)
        if (
            mobile.startswith("07") or mobile.startswith("01"))\
                and len(mobile) == 10:
            return "254"+mobile[1:]
        if mobile.startswith("254") and len(mobile) == 12:
            return mobile
        if (
            mobile.startswith("7") or mobile.startswith("1"))\
                and len(mobile) == 9:
            return "254"+mobile
            
        return mobile+"-invalid_phone_number"

    def save(self, *args, **kwargs):
        if not self.pk:
            self.code = str(uuid.uuid4()).upper()[:3]+'D'+str(self.username[-3:]).upper()
            # if self.phone_number is None:
            self.phone_number = self.format_mobile_no(self.username)

        super(User, self).save(*args, **kwargs)

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _
from django.contrib.auth import get_user_model

User = get_user_model()


class SignUpForm(UserCreationForm):
    """Prepares help texts, class and placeholder attributes.

    Define methods to increase and decrese token_count amount,
    betting and check if bet is possible.
    """
    

    # error_messages = {
    #     'invalid_code': _(
    #         "invalid code.The code doent exist"
    #     ),
    # }
    
    username = forms.CharField(
        max_length=50, required=True,
        label='',
        # help_text='E.g   07200200200 or 01200200200',
        widget=forms.TextInput(attrs={
            'class': 'form-control',
            'placeholder': 'Phone Number.  ie 071001000'
        }))

    # first_name = forms.CharField(max_length=30, required=False,
    #     label='', help_text='Optional',
    #     widget=forms.TextInput(attrs={
    #         'class': 'form-control',
    #         'placeholder': 'First name...'
    #     }))

    # last_name = forms.CharField(max_length=30, required=False,
    #     label='', help_text='Optional',
    #     widget=forms.TextInput(attrs={
    #         'class': 'form-control',
    #         'placeholder': 'Last name...'
    #     }))

    # phone_number = forms.CharField(max_length=150, required=True,
    #     label='',
    #     help_text='E.g   07200200200 or 01200200200',
    #     widget=forms.TextInput(attrs={
    #         'class': 'form-control',
    #         'placeholder': 'Phone Number...'
    #     }))

    email = forms.EmailField(
        max_length=254, required=True,
        label='',
        #  help_text='Required.Enter valid email.Required wen if you forot password.',
        widget=forms.EmailInput(attrs={
            'class': 'form-control',
            'placeholder': 'Email...'
        }))

    referer_code = forms.CharField(
        max_length=150,
        required=True,
        label='',
        help_text='Dont have ? Enter ADMIN',
        widget=forms.TextInput(attrs={
            'class': 'form-control',
            'placeholder': 'Enter your Refere code here'
        }))

    password1 = forms.CharField(
        required=True,
        label='',
        widget=forms.PasswordInput(attrs={
            'class': 'form-control',
            'placeholder': 'Password...'
        }))

    password2 = forms.CharField(
        required=True,
        label='',
        widget=forms.PasswordInput(attrs={
            'class': 'form-control',
            'placeholder': 'Confirm password...'
        }))

    class Meta:
        model = User
        fields = ('username', 'email', 'referer_code', 'password1', 'password2')

        # error_messages = {
        #     'referer_code': {'required': "Daru code required.Dont have ? Enter ADMIN"}
        #     }

    # def cleaned_daru_code(self):
    #     user =User.objects.get(username=self.username)
    #     if self.daru_code not in User.codes():
    #         raise ValidationError(
    #             self.error_messages['invalid_code'],
    #             code='invalid_code',
    #         )

users/templates/password/password_reset_complete.html
{% extends "dashboard/layouts/base.html" %}

{% block content %}

<div class='row'>
  <div class='col-md-2'></div>
  <div class='col-md-8'>
    <div class='text-info alert alert-info'>
      Your password has been set. You may go ahead and <a href="{% url 'users:login' %}">sign in</a> now.
    </div>
  </div>
</div>

{% endblock %}

users/templates/password/password_reset_confirm.html
{% extends "dashboard/layouts/base.html" %}

{% block content %}

  {% if validlink %}
  <div class="row">
    <div class="col-md-3"></div>
    <div class="col-md-6">
      <h2>Change password</h2>
      <hr>

      <form class="form-horizontal" role="form" method="POST">
        {% csrf_token %}

        {% for field in form %}
          <div class="form-group {% if field.errors %}has-error{% endif %}">
          <p>
            {% if field.help_text %}
            <div class="help-block text-info alert alert-info">
              <small>
                Your password can't be too similar to your other personal information, must contain at least 8 characters, can't be a commonly used password, can't be entirely numeric.
              </small>
            </div>
            {% endif %}

            {{ field }}
            <span class="help-block text-info">{{ field.label_tag }}</span>

            {% if field.errors %}
            <div class='text-danger alert alert-danger'>
              {{ field.errors|join:'<br />' }}
            </div>
            {% endif %}
          </p>

        {% endfor %}
        </div>
        <button type="submit" class="btn btn-success">Change password</button>
      </form>
    </div>
  </div>
  
  {% else %}

  <div class='row'>
    <div class='col-md-2'></div>
    <div class='col-md-8'>
      <div class='text-danger alert alert-danger'>
        The password reset link was invalid, possibly because it has already been used.
      Please request a new password reset.
      </div>
    </div>
  </div>

  {% endif %}

{% endblock %}

users/templates/password/password_reset_done.html
{% extends "dashboard/layouts/base.html" %}

{% block content %}

<div class='row'>
  <div class='col-md-2'></div>
  <div class='col-md-8'>
    <div class='btn btn-primary btn-block'>
      Check your email! We've emailed you instructions for setting your password, if an account exists with the email you entered.<br>
      You should receive them shortly.
    </div>
    <div class='btn btn-primary btn-block'>
      If you don't receive an email, please make sure you've entered the address you registered with,
      and check your spam folder!
    </div>
    <div class="float-right">
      <a class="btn btn-link" href="{% url 'users:password_reset' %}">Enter email again</a>
  </div>
  </div>
</div>

{% endblock %}

users/templates/password/password_reset_email.html
{% autoescape off %}
To initiate the password reset process for your {{ user.get_username }} Account,
click the link below:

{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}

If clicking the link above doesn't work, please copy and paste the URL in a new browser
window instead.

Sincerely,
The Daru Wheel Site Team
{% endautoescape %}

users/templates/password/password_reset_form.html
{% extends "dashboard/layouts/base.html" %}

{% block content %}

<!-- <div class="row">
  <div class="col-md-3"></div>
  <div class="col-md-6">
    <h2>Forgot password</h2>
    <hr>

    <form class="form-horizontal" role="form" method="POST">
      {% csrf_token %}

      {% for field in form %}
        <div class="form-group {% if field.errors %}has-error{% endif %}">
        <p>
          Enter {{field.label}} you reqister with here: {{ field}}

        {% if field.errors %}
        <div class='text-danger alert alert-danger'>{{ field.errors|join:'<br />' }}</div>
        {% endif %}

        {% if field.help_text %}
        <span class="help-block text-muted">
          <small>{{ field.help_text }}</small>
        </span>
        {% endif %}
        </p>

      {% endfor %}
      </div>
      <button type="submit" class="btn btn-success">Reset</button>
    </form>
  </div>
</div> -->




<div class="row">

  <div class="col-12">
    <div class="card card-chart">
        
      <!-- <div class="card-header ">
        <div class="row">
          <div class="col-sm-6 text-left">
            <h1 class="card-category">Please Login</h1>
            <h2 class="card-title">Please Login</h2>
          </div>
  
        </div>
      </div> -->
      <div class="card-body">
        <form class="form-horizontal" role="form" method="POST">
          {% csrf_token %}
    
          {% for field in form %}
            <div class="form-group {% if field.errors %}has-error{% endif %}">
            <p>
              Enter {{field.label}} you reqister with here: {{ field}}
    
            {% if field.errors %}
            <div class='text-danger alert alert-danger'>{{ field.errors|join:'<br />' }}</div>
            {% endif %}
    
            {% if field.help_text %}
            <span class="help-block text-muted">
              <small>{{ field.help_text }}</small>
            </span>
            {% endif %}
            </p>
    
          {% endfor %}
          </div>
          <button type="submit" class="btn btn-success">Reset</button>
        </form>



      </div>
    </div>
  </div>

</div>
    
{% endblock %}